### ISSUE TITLE
[Bug]: CI failed with run section

### ISSUE THREAD

**Issue by MasahiroSakoda** [MasahiroSakoda/dotfiles#246]
### Description

CI failed with wrong config

fix like this
```yml
        run: |
          run: rm '/usr/local/bin/2to3'
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
```
to
```yml
        run: |
          rm '/usr/local/bin/2to3'
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

```

### Expected behavior

pass CI

### Actual behavior

failed with error

### Steps to reproduce

run CI

### Environment

macos-latest
